services:
  postgres:
    image: postgres:16-alpine
    container_name: zsi-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bandhub_db
      POSTGRES_USER: bandhub_user
      POSTGRES_PASSWORD: bandhub_password
    volumes:
      - ./infra/postgres-data:/var/lib/postgresql/data
    networks:
      - bandhub-network
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: zsi-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - bandhub-network
    restart: always

networks:
  bandhub-network:
    driver: bridge